// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parks.Models;

namespace Parks.Migrations
{
    [DbContext(typeof(ParksContext))]
    [Migration("20191101165758_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Parks.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Location");

                    b.Property<string>("Name");

                    b.Property<int>("SquareMileage");

                    b.Property<string>("Terrain");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Description = "The hottest, driest and lowest of all the national parks in the United States.",
                            Location = "Eastern California; Nevada",
                            Name = "Death Valley National Park",
                            SquareMileage = 5262,
                            Terrain = "Harsh desert, salt-flats, sand dunes, badlands, valleys, canyons, mountains"
                        },
                        new
                        {
                            ParkId = 2,
                            Description = "The largest national park in the United States. This park includes a large portion of the Saint Elias Mountains, which include most of the highest peaks in the United States and Canada.",
                            Location = "Eastern region of South-central Alaska",
                            Name = "Wrangell-St. Elias National Park & Preserve",
                            SquareMileage = 20587,
                            Terrain = "Mountains, glaciers, rivers, tundra, forest, tidewaters, alpine"
                        },
                        new
                        {
                            ParkId = 3,
                            Description = "Established in 1872, it was the first national park in the United States. The volcanic plumbing beneath the park is still active, giving energy to more than ten thousand hot springs, mud pots, terraces, and geysers.",
                            Location = "Wyoming, Montana, Idaho",
                            Name = "Yellowstone National Park",
                            SquareMileage = 3471,
                            Terrain = "Mountains, canyons, rivers, waterfalls, forests"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
